# WebSocket server URL
SERVER_URL = "http://localhost:8000"

# OmniDimension API Configuration
OMNIDIM_API_KEY = "o3du0O4QJIRSjTYDwe9-uWuZ7ptaMMQu3rkXlUv8-vo"
OMNIDIM_AGENT_ID = 1  # Default agent ID, update if you have a specific one
